env:
  map_path: maps/8x8/basesWorkers8x8.xml
  max_steps: 2000
  interval: 100
  record_video: true
  display: false

llm:
  temperature: 0
  max_tokens: 1024

players:
  - model: Qwen2.5-72B-Instruct
    prompt: few-shot-w-strategy
    temperature: ${llm.temperature}
    max_tokens: ${llm.max_tokens}

  - model: coacAI
    prompt: zero-shot
    temperature: ${llm.temperature}
    max_tokens: ${llm.max_tokens}
