EXAMPLES:
  - |
    START OF TASK
    [Harvest Mineral](0, 0)  # one worker harvests minerals
    [Harvest Mineral](0, 0)  # another worker harvests minerals
    [Produce Unit](worker, east)
    [Produce Unit](worker, south)
    [Produce Unit](worker, east)
    [Produce Unit](worker, south)
    [Build Building](barracks, (0, 3), resource >= 7)
    [Produce Unit](ranged, east)
    [Produce Unit](ranged, south)
    [Produce Unit](ranged, east)
    [Produce Unit](ranged, south)
    [Attack Enemy](worker, worker)  # when no barracks use worker to attack
    [Attack Enemy](worker, worker)
    [Attack Enemy](worker, worker)
    [Attack Enemy](worker, worker)
    [Attack Enemy](worker, barracks)
    [Attack Enemy](worker, base)
    [Attack Enemy](ranged, worker)  # when has barracks use ranged to attack
    [Attack Enemy](ranged, worker)
    [Attack Enemy](ranged, worker)
    [Attack Enemy](ranged, worker)
    [Attack Enemy](ranged, barracks)
    [Attack Enemy](ranged, base)
    END OF TASK

  - |
    START OF TASK
    [Harvest Mineral](7, 7)  # one worker harvests minerals
    [Harvest Mineral](7, 7)  # another worker harvests minerals
    [Produce Unit](worker, west)
    [Produce Unit](worker, north)
    [Produce Unit](worker, west)
    [Produce Unit](worker, north)
    [Build Building](barracks, (7, 4), resource >= 7)
    [Produce Unit](ranged, west)
    [Produce Unit](ranged, north)
    [Produce Unit](ranged, west)
    [Produce Unit](ranged, north)
    [Attack Enemy](worker, worker)
    [Attack Enemy](worker, worker)
    [Attack Enemy](worker, worker)
    [Attack Enemy](worker, worker)
    [Attack Enemy](worker, barracks)
    [Attack Enemy](worker, base)
    [Attack Enemy](ranged, worker)
    [Attack Enemy](ranged, worker)
    [Attack Enemy](ranged, worker)
    [Attack Enemy](ranged, worker)
    [Attack Enemy](ranged, barracks)
    [Attack Enemy](ranged, base)
    END OF TASK
