INSTRUCTION: |
  You are an RTS game master tasked with designing a robust strategy based on the provided parameterized framework.

INTRODUCTION: |
  
  # Parameterized Strategy
  A strategy consists of several dimensions defined by specific parameters:

  1. **Economic Feature** focuses on how many workers to harvest in the game.
    - Parameter: Number of harvesting workers
    - Feature Space: {{1, 2}}

  2. **Barracks Feature** determines when to build barracks.  You can construct barracks when resources are greater than or equal to a specific threshold (N), or not build them at all (False).
    - Parameter: Timing of construction (resource quantity)
    - Feature Space: {{resource >= N, False}}

  3. **Military Feature** outlines the strategy for combining different unit types used for attack or defense, specifying which units to produce.
    - Parameter: Combination of unit types
    - Feature Space: {{Worker, Ranged and Worker, Ranged and Light, ...}}

  4. **Aggressiveness Feature** indicates whether the player's strategy is inclined toward aggressive play (attacking) or defensive play (holding ground).
  - Parameter: Aggressiveness
  - Feature Space: {{True, False}  # {Aggressive, Defensive}}

  5. **Aggression Features** define the target priority during an attack if the Aggressiveness Feature is set to True, focusing the military on attacking specific enemy unit types.
    - Parameter: Priority attack target
    - Feature Space: {{Ranged > Worker, Base > Barracks > Worker, ...}}
  
  6. **Defense Features** outline critical defense areas if the Aggressiveness Feature is set to False, specifying where military units are deployed.
    - Parameter: Defense area, defined by top left and bottom right coordinates
    - Feature Space: {{(x1, y1), (x2, y2)}}

EXAMPLES: |
  
  # Example
  Here is a parameterized strategy example for your reference. You have to output the same format as the example:

  ## Strategy
  - Economic Features: 1  # Two workers for mineral harvesting
  - Barracks Features: resource >= 7  # Build barracks when resources reach 7 or more
  - Military Features: Ranged and Worker  # Combination of ranged and worker units
  - Aggressiveness Feature: True  # Aggressive play
  - Aggression Features: Ranged > Worker  # Prioritize attacking enemy ranged units over workers
  - Defense Features: None  # Aggressive strategy, no defense areas

  ## Description
  - Allocate two workers for mineral harvesting to support ongoing economic growth.
  - Construct barracks once resources exceed 7.
  - Simultaneously produce ranged and worker units to maintain a balanced military.
  - Use the unit types specified in the Military Features (Ranged and Worker) to prioritize attacking enemy ranged units and workers.
  - No designated defense areas; do not deploy units defensively.

OPPONENT: |
 
  # Opponent Features
  Based on the past battle history, the characteristics of the opponent are analyzed as follows:
  {opponent}

TIPS: |
  
  # Tips for Developing a Strategy:
  1. Analyze the weaknesses of your opponent.
  2. Consider the relationships and constraints between unit types.
  3. Ensure that the strategy parameters are valid.
  4. Evaluate the coherence of the overall strategy composed of different features.
  5. Do not output any irrelevant content.

START: |
  
  Approach your task step by step.
