INSTRUCTION: |
  You are an RTS game expert tasked with planning a winning task plan in MicroRTS based on the provided scenario.

INTRODUCTION: |
  
  # Game Manual
  Here are the core rules and mechanics you need to follow: 
  This is a 2-player grid-based game where all units occupy 1x1 tiles. Each player controls units and can create more by spending a single resource type, which acts as money. The grid position coordinates range from 0 to grid size minus 1.

  Here is the game units description:
  - Resource: A non-player unit that provides resources.
  - Base: 10 HP, costs 10 resources, and takes 250 time units to build. Can produce Workers.
  - Barracks: 4 HP, costs 5 resources, and takes 200 time units to build. Can produce Light, Heavy, or Ranged units.
  - Worker: 1 HP, costs 1 resource, takes 50 time units to build. Can [Attack Enemy](1 damage), and harvest mineral.
  - Light Unit: 4 HP, costs 2 resources, takes 80 time units to build. Can [Attack Enemy] (2 damage).
  - Heavy Unit: 4 HP, costs 2 resources, takes 120 time units to build. Can [Attack Enemy] (4 damage).
  - Ranged Unit: 1 HP, costs 2 resources, takes 100 time units to build. Can [Attack Enemy] from 3 distance (1 damage, range 3).

  # Task Space
  Develop a winning task plan using allowed task space: 
  You are only allowed to utilize the specified tasks to devise your strategy. All tasks will only be assigned to one corresponding unit, so if you want multiple units to work together, please generate multiple repeated tasks.
  Each task comprises a task name (enclosed in square brackets, e.g. "[Harvest Mineral]") and task parameters (enclosed in parentheses, e.g. "(0, 0)"). 
  Your game plan should be a list of tasks, with "START OF TASK" and "END OF TASK" marking the beginning and end of the list, for example:
  START OF TASK
  [Harvest Mineral] (0, 0)
  [Produce Unit] (worker, 0)
  ...
  END OF TASK

  Here are the available tasks and their descriptions:
  - [Harvest Mineral] (x, y): Assign one worker to harvest resources from the mineral field located at (x, y). Note that this task is a continued task, which means that the worker will continue to harvest resources until mineral disappear or the game ends.
  - [Produce Unit] (unit_type, direction): Produce a unit of the specified type ("worker", "light", "heavy", or "ranged") in the specified direction ("north", "east", "south", or "west").
  - [Build Building] (building_type, (x, y), condition): Constructs a specified building type ("base" or "barracks") at coordinates (x, y) if the condition is met. The condition must be a resource-related expression, like resource >= 7, or set to False, indicating that construction will never occur.
  - [Deploy Unit] (unit_type, (x, y)): Deploy a unit of the specified type to the specified location (x, y). One location can only have one unit deployed.
  - [Attack Enemy] (unit_type, ENEMY_type): Use a unit of a specified type ("worker", "light", "heavy", or "ranged") to attack an enemy unit of a specified type ("worker", "light", "heavy", "ranged", "base", or "barracks").

  Please note that your plans will be executed in order, so the one listed first will be executed first. You should strictly follow the parameter format and avoid outputting extra parameters.
  If you produce a unit type, be sure to assign a task to that unit type, otherwise they will block the entrance to the base or barracks, preventing the next unit from coming out.
  Please pay attention to the actual location of your current base. If you need to harvest resources, please go to the nearest mine location.

EXAMPLES: |
  
  # Examples
  You can refer to the following examples for guidance: 
  {examples}

OPPONENT: |
  
  # Opponent Profile
  Based on previous encounters, here is a summary of the opponent strategy and tactics: 
  {opponent}

STRATEGY: |
  
  # Parameterized Strategy Space
  A strategy consists of several dimensions defined by specific parameters:

  1. **Economic Feature** focuses on how many workers to harvest in the game.
    - Parameter: Number of harvesting workers
    - Feature Space: {{1, 2}}

  2. **Barracks Feature** determines when to build barracks.  You can construct barracks when resources are greater than or equal to a specific threshold (N), or not build them at all (False).
    - Parameter: Timing of construction (resource quantity)
    - Feature Space: {{resource >= N, False}}, where 5 <= N <= 10

  3. **Military Feature** outlines the strategy for combining different unit types used for attack or defense, specifying which units to produce.
    - Parameter: Combination of unit types, including Worker, Heavy, Light, Ranged.
    - Feature Space: {{Worker, Ranged and Worker, Ranged and Light and Worker, ...}}

  4. **Aggression Feature** indicates whether the player's strategy is inclined toward aggressive play (attacking) or defensive play (holding ground).
  - Parameter: Aggression
  - Feature Space: {{True, False}}  # {{Aggressive, Defensive}}

  5. **Attack Feature** define the target priority during an attack if the Aggressiveness Feature is set to True, focusing the military on attacking specific enemy unit types.
    - Parameter: Priority attack target
    - Feature Space: {{Building, Unit}}  # {{Attack Buildings, Attack Units (including Workers, Heavy, Light, Ranged)}}
  
  6. **Defense Feature** specifies the distance of the defense perimeter from the base, indicating where military units are deployed if the Aggressive feature is set to False.
    - Parameter: Distance from base
    - Feature Space: {{1, 2, 3, 4}}  # {{Close, Medium, Far, Very Far}}
  
  # Strategy
  The following is a detailed strategy you should strictly follow:
  {strategy}

TIPS: |
  
  # Tips
  Here are some valuable suggestions that you should definitely consider: 
  {tips}

START: |
  
  # Battlefield Situation
  Here is the description of the **current situation**: 
  {observation}
  
  You are now **player {player_id}**. Please create a task plan to win the game based on the current situation. 
  Keep in mind that you should also anticipate future scenarios, as your opponent will continue to play. If you adopt an aggressive strategy, you'll need to incorporate more attack tasks to counter their newly produced units.
  Output only the task plan in the specified format, without any extra content.