INSTRUCTION: |
  You are an RTS game master tasked with designing a robust strategy based on the provided parameterized framework.

MANUAL: |
  
  ## Game Manual
  Here are the core rules and mechanics you need to follow: 
  This is a 2-player grid-based game where all units occupy 1x1 tiles. Each player controls units and can create more by spending a single resource type, which acts as money. The grid position coordinates range from 0 to grid size minus 1.

  Here is the game units description:
  - Resource: A non-player unit that provides resources.
  - Base: 10 HP, costs 10 resources, and takes 250 time units to build. Can produce Workers.
  - Barracks: 4 HP, costs 5 resources, and takes 200 time units to build. Can produce Light, Heavy, or Ranged units.
  - Worker: 1 HP, costs 1 resource, takes 50 time units to build. Can [Attack Enemy](1 damage), and harvest mineral.
  - Light Unit: 4 HP, costs 2 resources, takes 80 time units to build. Can [Attack Enemy] (2 damage).
  - Heavy Unit: 4 HP, costs 2 resources, takes 120 time units to build. Can [Attack Enemy] (4 damage).
  - Ranged Unit: 1 HP, costs 2 resources, takes 100 time units to build. Can [Attack Enemy] from 3 distance (1 damage, range 3).

  ## Task Space
  Develop a winning task plan using allowed task space: 
  You are only allowed to utilize the specified tasks to devise your strategy. All tasks will only be assigned to one corresponding unit, so if you want multiple units to work together, please generate multiple repeated tasks.
  Each task comprises a task name (enclosed in square brackets, e.g. "[Harvest Mineral]") and task parameters (enclosed in parentheses, e.g. "(0, 0)"). 
  Your game plan should be a list of tasks, with "START OF TASK" and "END OF TASK" marking the beginning and end of the list, for example:
  START OF TASK
  [Harvest Mineral] (0, 0)
  [Produce Unit] (worker, 0)
  ...
  END OF TASK

  Here are the available tasks and their descriptions:
  - [Harvest Mineral] (x, y): Assign one worker to harvest resources from the mineral field located at (x, y).
  - [Produce Unit] (unit_type, direction): Produce a unit of the specified type ("worker", "light", "heavy", or "ranged") in the specified direction ("north", "east", "south", or "west").
  - [Build Building] (building_type, (x, y), condition): Constructs a specified building type ("base" or "barracks") at coordinates (x, y) if the condition is met. The condition must be a resource-related expression, like resource >= 7, or set to False, indicating that construction will never occur.
  - [Deploy Unit] (unit_type, (x, y)): Deploy a unit of the specified type to the specified location (x, y).
  - [Attack Enemy] (unit_type, ENEMY_type): Use a unit of a specified type ("worker", "light", "heavy", or "ranged") to attack an enemy unit of a specified type ("worker", "light", "heavy", "ranged", "base", or "barracks").

  Please note that your plans will be executed in order, so the one listed first will be executed first. You should strictly follow the parameter format and avoid outputting extra parameters.
  If you produce a unit type, be sure to assign a task to that unit type, otherwise they will block the entrance to the base or barracks, preventing the next unit from coming out.
  Please pay attention to the actual location of your current base. If you need to harvest resources, please go to the nearest mine location.

INTRODUCTION: |
  
  # Parameterized Strategy
  A strategy consists of several dimensions defined by specific parameters:

  1. **Economic Feature** focuses on how many workers to harvest in the game.
    - Parameter: Number of harvesting workers
    - Feature Space: {{1, 2}}

  2. **Barracks Feature** determines when to build barracks.  You can construct barracks when resources are greater than or equal to a specific threshold (N), or not build them at all (False).
    - Parameter: Timing of construction (resource quantity)
    - Feature Space: {{resource >= N, False}}

  3. **Military Feature** outlines the strategy for combining different unit types used for attack or defense, specifying which units to produce.
    - Parameter: Combination of unit types
    - Feature Space: {{Worker, Ranged and Worker, Ranged and Light, ...}}

  4. **Aggressiveness Feature** indicates whether the player's strategy is inclined toward aggressive play (attacking) or defensive play (holding ground).
  - Parameter: Aggressiveness
  - Feature Space: {{True, False}  # {Aggressive, Defensive}}

  5. **Aggression Features** define the target priority during an attack if the Aggressiveness Feature is set to True, focusing the military on attacking specific enemy unit types.
    - Parameter: Priority attack target
    - Feature Space: {{Ranged > Worker, Base > Barracks > Worker, ...}}
  
  6. **Defense Features** outline critical defense areas if the Aggressiveness Feature is set to False, specifying where military units are deployed.
    - Parameter: Defense area, defined by top left and bottom right coordinates
    - Feature Space: {{(x1, y1), (x2, y2)}}

EXAMPLES: |
  
  # Example
  Here is a parameterized strategy example for your reference. You have to output the same format as the example:

  ## Strategy
  - Economic Features: 2  # Two workers for mineral harvesting
  - Barracks Features: resource >= 7  # Build barracks when resources reach 7 or more
  - Military Features: Ranged and Worker  # Combination of ranged and worker units
  - Aggressiveness Feature: True  # Aggressive play
  - Aggression Features: Ranged > Worker  # Prioritize attacking enemy ranged units over workers
  - Defense Features: None  # Aggressive strategy, no defense areas

  ## Description
  You should:
  - Allocate two workers for mineral harvesting to support ongoing economic growth.
  - Construct barracks once resources exceed 7.
  - Keep producing your military (ranged and worker) more units is better.
  - Only produce ranged and worker units.
  - Prioritize attacking enemy ranged units over workers.
  - Send both workers and ranged units to attack, rather than just using a single type.
  - Omit designated defense areas; do not deploy units, just go attacking.

  You should not:
  - Do not build additional barracks.
  - Do not produce any other units.
  - Do not plan deploy task.

basesWorkers8x8_MAP: |
  
  # Map Initialization Sate
  The Game map is 8x8 grid
  Available Mineral Fields: 2
  - Mineral(0, 0), resources: 20
  - Mineral(7, 7), resources: 20
  Player 0 State:
  - base(1, 2), action: noop
  - worker(1, 1), action: noop
  Player 1 State:
  - base(6, 5), action: noop
  - worker(6, 6), action: noop

EXIST_STRATEGY: |
  
  # Existing Strategy
  There are already existing strategies as follows, which you should not repeated:
  {exist_strategy}

OPPONENT: |
 
  # Opponent Features
  Based on the past battle history, the characteristics of the opponent are analyzed as follows:
  {opponent}

TIPS: |
  
  # Tips for Developing a Strategy:
  1. Analyze the weaknesses of your opponent.
  2. Consider the relationships and constraints between unit types.
  3. Ensure that the strategy parameters are valid.
  4. Evaluate the coherence of the overall strategy composed of different features.
  5. Do not output any irrelevant content.

START: |
  
  Approach your task step by step.
